name: deploy_installer_prod

on:
  workflow_dispatch: # 手動実行用

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CLASP
        uses: ./.github/actions/setup-clasp
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          id_token: ${{ secrets.ID_TOKEN }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}

      - name: Copy backend.js to installer directory
        run: |
          # backend.jsをinstallerディレクトリにコピー
          cp webapp/backend.js installer/backend.js
          echo "backend.jsをinstallerディレクトリにコピーしました"

      - name: Create & Push Bound Apps Script
        run: |
          # installerディレクトリに移動
          cd installer

          # スプレッドシートに紐づくApps Scriptプロジェクトを作成
          clasp create --title "家計簿入力支援ツール" --parentId "${{ secrets.PROD_TARGET_SPREADSHEET_ID }}"

          # コードをpush
          clasp push -f

          echo "新しい家計簿入力支援ツールがインストールされました。古い家計簿入力支援ツールプロジェクトは削除してください。"

