name: deploy_webapp_dev

on:
  workflow_dispatch: # 手動実行用

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CLASP
        uses: ./.github/actions/setup-clasp
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          id_token: ${{ secrets.ID_TOKEN }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}

      - name: Create .clasp.json for development
        run: |
          cat > webapp/.clasp.json <<EOF
          {
            "scriptId": "${{ secrets.DEV_CLASP_SCRIPT_ID }}",
            "rootDir": "",
            "scriptExtensions": [
              ".js",
              ".gs"
            ],
            "htmlExtensions": [
              ".html"
            ],
            "jsonExtensions": [
              ".json"
            ],
            "filePushOrder": [],
            "skipSubdirectories": false
          }
          EOF

      - name: Push & Update Apps Script
        run: |
          # webappディレクトリに移動
          cd webapp

          # コードを push
          clasp push -f

          # 既存デプロイを更新（Webアプリケーションとして）
          clasp deploy --deploymentId ${{ secrets.DEV_CLASP_DEPLOYMENT_ID }} --type webapp

