name: deploy_webapp_prod

on:
  workflow_dispatch: # 手動実行用

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CLASP
        uses: ./.github/actions/setup-clasp
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          id_token: ${{ secrets.ID_TOKEN }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}

      - name: Push & Update Apps Script
        run: |
          # webappディレクトリに移動
          cd webapp

          # コードを push
          clasp push -f

          # 既存デプロイを更新（Webアプリケーションとして）
          clasp deploy --deploymentId ${{ secrets.PROD_CLASP_DEPLOYMENT_ID }} --type webapp

